-- The teachers' question bank, as the office wrote it.
--
-- Thirty situations from a teacher's morning: arriving, the assembly, the
-- register, the toilet pass, lunch, the Rose of the Day and how a child who
-- keeps coming late or unwashed is spoken to. The Hindi is the wording the
-- office gave; the English is a translation of it, because a paper is read in
-- whichever language the teacher is comfortable with.
--
-- A question is recognised by its Hindi wording, so re-running this adds
-- nothing twice and an edit made in the app is never overwritten.
CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_q_text
  ON staff_test_questions (for_role, question_hi);

INSERT INTO staff_test_questions
  (for_role, topic, question_en, question_hi, options_en, options_hi, correct_index)
VALUES
  ('teacher', 'Punctuality',
   'School starts at 7:00 am. By what time should the teacher have arrived?',
   'स्कूल का समय सुबह 7:00 बजे है। शिक्षक को कितने बजे तक पहुँच जाना चाहिए?',
   ARRAY['At 7:00', 'At 7:05', 'At 6:55', 'At 7:10'],
   ARRAY['7:00 बजे', '7:05 बजे', '6:55 बजे', '7:10 बजे'], 2),
  ('teacher', 'Class preparation',
   'The teacher has reached school but has not prepared today''s class. What should she do?',
   'शिक्षक स्कूल पहुँच गईं, लेकिन आज की कक्षा की तैयारी नहीं की है। उन्हें क्या करना चाहिए?',
   ARRAY['Give the children any work at all', 'Prepare the subject there and then, and start teaching', 'Send the children home', 'Ask another teacher to take the whole class'],
   ARRAY['बच्चों को कोई भी काम दे देना', 'उसी समय विषय की तैयारी करना और फिर पढ़ाना शुरू करना', 'बच्चों को छुट्टी दे देना', 'दूसरे शिक्षक से पूरी कक्षा लेने को कहना'], 1),
  ('teacher', 'Assembly',
   'Two children have been given the job of lining everyone up at prayer. What should the teacher do?',
   'प्रार्थना के समय दो बच्चों को लाइन लगाने की जिम्मेदारी दी गई है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Leave the whole arrangement to the children and sit down', 'Take the children''s help while keeping an eye on the arrangement herself', 'Only lead the prayer', 'Scold the children'],
   ARRAY['बच्चों को पूरी व्यवस्था करने देकर खुद बैठ जाना', 'बच्चों की मदद लेते हुए खुद भी व्यवस्था पर नजर रखना', 'केवल प्रार्थना करवाना', 'बच्चों को डाँटना'], 1),
  ('teacher', 'Assembly',
   'Prayer is about to start but the speaker is in a child''s hands. What should the teacher do?',
   'प्रार्थना शुरू होने वाली है, लेकिन स्पीकर किसी बच्चे के हाथ में है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Let the child keep the speaker', 'Take the speaker into the teacher''s own hands', 'Switch the speaker off', 'Hold the prayer without the speaker'],
   ARRAY['बच्चे को ही स्पीकर रखने देना', 'स्पीकर शिक्षक के हाथ में लेना', 'स्पीकर बंद कर देना', 'बिना स्पीकर प्रार्थना करवाना'], 1),
  ('teacher', 'Assembly',
   'During prayer the teacher is standing in one place and some children are talking among themselves. What should she do?',
   'प्रार्थना के दौरान शिक्षक एक ही जगह खड़ी हैं और कुछ बच्चे आपस में बात कर रहे हैं। क्या करना चाहिए?',
   ARRAY['Quieten the children from where she stands', 'Move among the children and keep an eye on discipline', 'Stop the prayer', 'Send a child to supervise'],
   ARRAY['वहीं से बच्चों को चुप कराना', 'बच्चों के बीच घूमते हुए अनुशासन पर नजर रखना', 'प्रार्थना बंद कर देना', 'किसी बच्चे को निगरानी के लिए भेजना'], 1),
  ('teacher', 'Assembly',
   'School starts at 7:00. By when must the prayer photograph be sent?',
   'स्कूल 7:00 बजे शुरू होता है। प्रार्थना की फोटो कब तक भेजनी है?',
   ARRAY['7:05', 'By 7:10', 'By 7:20', 'By 8:00'],
   ARRAY['7:05 बजे', '7:10 बजे तक', '7:20 बजे तक', '8:00 बजे तक'], 1),
  ('teacher', 'Attendance',
   'It is 7:10 am and attendance has not yet been written on the whiteboard. What should the teacher do?',
   'सुबह 7:10 बजे हो चुके हैं और व्हाइटबोर्ड पर अटेंडेंस अभी नहीं लिखी गई है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Write it after lunch', 'Write it the next day', 'Complete the attendance at once', 'Put it straight into the software'],
   ARRAY['लंच के बाद लिखना', 'अगले दिन लिखना', 'तुरंत अटेंडेंस पूरी करना', 'सॉफ्टवेयर में ही डाल देना'], 2),
  ('teacher', 'Attendance',
   'Attendance is on the whiteboard, but it has not been updated in the software by 7:20. What should be done?',
   'व्हाइटबोर्ड पर अटेंडेंस पूरी हो गई है, लेकिन 7:20 बजे तक सॉफ्टवेयर में अपडेट नहीं हुई। क्या करना चाहिए?',
   ARRAY['Update it the next day', 'Update the software at once', 'Keep it on the whiteboard only', 'Have a child do it'],
   ARRAY['अगले दिन अपडेट करना', 'तुरंत सॉफ्टवेयर में अपडेट करना', 'केवल व्हाइटबोर्ड पर रखना', 'किसी बच्चे से करवाना'], 1),
  ('teacher', 'Toilet pass',
   'A girl wants to go to the toilet and two girls have already gone with passes. What should the teacher do?',
   'एक लड़की टॉयलेट जाना चाहती है और पहले से दो लड़कियाँ पास लेकर गई हुई हैं। शिक्षक को क्या करना चाहिए?',
   ARRAY['Send the third child as well', 'Send all three together', 'Keep to the limit of two and let the first children come back', 'Send a boy along with her'],
   ARRAY['तीसरी बच्ची को भी भेज देना', 'तीनों को एक साथ भेज देना', 'दो बच्चों की सीमा का ध्यान रखते हुए पहले बच्चों के वापस आने देना', 'किसी लड़के को साथ भेजना'], 2),
  ('teacher', 'Toilet pass',
   'A child has no toilet pass and wants to go to the toilet. What should the teacher do?',
   'एक बच्चे के पास टॉयलेट पास नहीं है और वह टॉयलेट जाना चाहता है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Let him go without telling anyone', 'Arrange a toilet pass and then send him', 'Scold him', 'Stop him from going to the toilet for ever'],
   ARRAY['उसे बिना बताए जाने देना', 'टॉयलेट पास की व्यवस्था करके भेजना', 'उसे डाँटना', 'हमेशा के लिए टॉयलेट जाने से रोक देना'], 1),
  ('teacher', 'Lunch',
   'At lunch the children have sat down in separate little groups. What should the teacher do?',
   'लंच के समय बच्चे अलग-अलग छोटे समूहों में बैठ गए हैं। शिक्षक को क्या करना चाहिए?',
   ARRAY['Let them eat where they are', 'Ask the children to make one circle and sit together', 'Seat only the well-behaved children together', 'Stop lunch'],
   ARRAY['उन्हें वहीं खाने देना', 'बच्चों को एक सर्कल बनाकर साथ बैठने के लिए कहना', 'केवल अच्छे बच्चों को एक साथ बैठाना', 'लंच बंद कर देना'], 1),
  ('teacher', 'Lunch',
   'A child eats alone, away from the others, every day. What should the teacher do?',
   'एक बच्चा रोज दूसरों से अलग बैठकर खाना खाता है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Leave him alone', 'Scold him', 'Explain kindly and bring him into the children''s circle', 'Take his lunch away'],
   ARRAY['उसे अकेला छोड़ देना', 'उसे डाँटना', 'प्यार से समझाकर बच्चों के सर्कल में शामिल करना', 'उसका लंच ले लेना'], 2),
  ('teacher', 'Rose of the Day',
   'Today a child came on time, was clean and stayed disciplined all day. What should the teacher do?',
   'आज एक बच्चा समय पर आया, साफ-सुथरा था और पूरे दिन अनुशासन में रहा। शिक्षक को क्या करना चाहिए?',
   ARRAY['Give him the Rose of the Day award', 'Give him extra work', 'Send him home', 'Only telephone his parents'],
   ARRAY['उसे “आज का गुलाब Award” देना', 'उसे कोई अतिरिक्त काम देना', 'उसे घर भेज देना', 'केवल उसके माता-पिता को फोन करना'], 0),
  ('teacher', 'Rose of the Day',
   'After winning the Rose of the Day, should the same child be given the award again the next day?',
   '“आज का गुलाब Award” मिलने के बाद अगले दिन उसी बच्चे को फिर Award देना चाहिए?',
   ARRAY['Yes, if he is a good child', 'Yes, because he won last time', 'No — the next day another deserving child should be chosen', 'It should go to the teacher''s favourite child'],
   ARRAY['हाँ, अगर वह अच्छा बच्चा है', 'हाँ, क्योंकि वह पिछली बार जीता था', 'नहीं, अगले दिन किसी दूसरे योग्य बच्चे को चुनना चाहिए', 'केवल शिक्षक की पसंद के बच्चे को देना चाहिए'], 2),
  ('teacher', 'Rose of the Day',
   'A child is very good at studies but came very late today and was not disciplined. Should he get today''s rose?',
   'एक बच्चा पढ़ाई में बहुत अच्छा है, लेकिन आज बहुत देर से आया और अनुशासन में भी नहीं रहा। क्या उसे आज का गुलाब देना चाहिए?',
   ARRAY['Yes, because he is good at studies', 'Yes, because he is always good', 'No — coming on time and behaving well count for the award too', 'Yes, just because he is a small child'],
   ARRAY['हाँ, क्योंकि वह पढ़ाई में अच्छा है', 'हाँ, क्योंकि वह हमेशा अच्छा रहता है', 'नहीं, Award के लिए समय पर आना और अच्छा व्यवहार भी जरूरी है', 'केवल इसलिए देना चाहिए क्योंकि वह छोटा बच्चा है'], 2),
  ('teacher', 'Rose of the Day',
   'How can the teacher encourage children to become the Rose of the Day?',
   'शिक्षक बच्चों को “आज का गुलाब” बनने के लिए कैसे प्रेरित कर सकती हैं?',
   ARRAY['By praising only one child', 'By telling the children that coming on time, staying clean and being disciplined all matter', 'By frightening them', 'By giving the chance only to children who are good at studies'],
   ARRAY['केवल एक बच्चे की तारीफ करके', 'बच्चों को बताकर कि समय पर आना, साफ रहना और अनुशासन में रहना जरूरी है', 'बच्चों को डराकर', 'केवल पढ़ाई में अच्छे बच्चों को मौका देकर'], 1),
  ('teacher', 'Lateness',
   'A child comes late to school every day. What should the teacher do?',
   'एक बच्चा रोज स्कूल देर से आता है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Scold him every day', 'Give him the job of picking up leaves and call the parents in to explain', 'Remove him from school', 'Stop marking his attendance'],
   ARRAY['उसे रोज डाँटना', 'उसे पत्ते बिनने का काम देना और माता-पिता को बुलाकर समझाना', 'उसे स्कूल से निकाल देना', 'उसकी अटेंडेंस लगाना बंद कर देना'], 1),
  ('teacher', 'Lateness',
   'While speaking to the parents of a child who comes late, what should the teacher say?',
   'देर से आने वाले बच्चे के माता-पिता से बात करते समय शिक्षक को क्या कहना चाहिए?',
   ARRAY['“You don''t care about your child.”', '“When you are not late for your own work, send the children on time too.”', '“Your child will not come to school now.”', '“This is your fault.”'],
   ARRAY['“आप अपने बच्चे की परवाह नहीं करते।”', '“जब आप अपने काम में देर नहीं करते, तो बच्चों को भी समय पर भेजिए।”', '“अब आपका बच्चा स्कूल नहीं आएगा।”', '“यह आपकी गलती है।”'], 1),
  ('teacher', 'Lateness',
   'A child who came late says, “Mummy could not wake me in the morning.” What should the teacher explain?',
   'एक बच्चा देर से आने के बाद कहता है, “मम्मी मुझे सुबह नहीं उठा पाईं।” शिक्षक को क्या समझाना चाहिए?',
   ARRAY['Waking the child and sending him to school on time is the parents'' responsibility too', 'The child has no responsibility', 'It is the school''s responsibility', 'He need not come to school'],
   ARRAY['समय पर उठाना और स्कूल भेजना माता-पिता की जिम्मेदारी भी है', 'बच्चे की कोई जिम्मेदारी नहीं है', 'स्कूल की जिम्मेदारी है', 'उसे स्कूल आने की जरूरत नहीं है'], 0),
  ('teacher', 'Cleanliness',
   'A child has come to school without washing his face and hands. What should the teacher do?',
   'सुबह एक बच्चा बिना चेहरा और हाथ धोए स्कूल आया है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Shame him in front of everyone', 'Explain cleanliness kindly and have him wash his hands and face', 'Send him straight home', 'Give him an award'],
   ARRAY['उसे सबके सामने शर्मिंदा करना', 'प्यार से स्वच्छता के बारे में समझाना और हाथ-मुँह धुलवाना', 'उसे तुरंत घर भेज देना', 'उसे Award दे देना'], 1),
  ('teacher', 'Cleanliness',
   'A child has not come in clean clothes. What is the teacher''s right response?',
   'एक बच्चा साफ कपड़ों में नहीं आया है। शिक्षक की सही प्रतिक्रिया क्या होगी?',
   ARRAY['Make fun of him in front of everyone', 'Explain kindly that coming in clean clothes matters', 'Seat him away from the other children', 'Stop teaching him'],
   ARRAY['सबके सामने उसका मजाक बनाना', 'प्यार से समझाना कि साफ कपड़ों में आना जरूरी है', 'उसे दूसरे बच्चों से अलग बैठाना', 'उसे पढ़ाना बंद कर देना'], 1),
  ('teacher', 'Cleanliness',
   'A child has come without oiling his hair. What should the teacher do?',
   'एक बच्चा बालों में तेल लगाए बिना आया है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Scold him', 'Explain the habit of staying clean and tidy', 'Give him an award', 'Send him home'],
   ARRAY['उसे डाँटना', 'स्वच्छ और व्यवस्थित रहने की आदत समझाना', 'उसे Award देना', 'उसे घर भेज देना'], 1),
  ('teacher', 'Assembly',
   'The teacher forgot to take the prayer photograph and it is now 7:12. What should she do?',
   'प्रार्थना की फोटो लेना शिक्षक भूल गईं और अब 7:12 हो चुके हैं। क्या करना चाहिए?',
   ARRAY['Not send a photograph at all', 'Take and send the photograph at once, and watch the time in future', 'Send the next day''s photograph', 'Get an old photograph from a child'],
   ARRAY['फोटो बिल्कुल न भेजें', 'तुरंत फोटो लेकर भेजें और आगे समय का ध्यान रखें', 'अगले दिन की फोटो भेज दें', 'किसी बच्चे से पुरानी फोटो मँगाएँ'], 1),
  ('teacher', 'Discipline',
   'The teacher sees some children stepping out of line during prayer. What should she do?',
   'शिक्षक देखती हैं कि कुछ बच्चे प्रार्थना के दौरान लाइन से बाहर हो रहे हैं। उन्हें क्या करना चाहिए?',
   ARRAY['Only watch from a distance', 'Go among the children and put the line right', 'Stop the prayer', 'Punish the children'],
   ARRAY['केवल दूर से देखना', 'बच्चों के बीच जाकर व्यवस्था ठीक करना', 'प्रार्थना रोक देना', 'बच्चों को सजा देना'], 1),
  ('teacher', 'Lunch',
   'At lunch two children are quarrelling because each wants to sit in a different group. What should the teacher do?',
   'लंच के समय दो बच्चे आपस में झगड़ रहे हैं क्योंकि दोनों अलग-अलग समूह में बैठना चाहते हैं। शिक्षक को क्या करना चाहिए?',
   ARRAY['Feed them separately', 'Explain calmly and seat all the children in one circle', 'Take away both their lunches', 'Ignore the quarrel'],
   ARRAY['दोनों को अलग-अलग खाना खिलाना', 'शांतिपूर्वक समझाकर सभी बच्चों को एक सर्कल में बैठाना', 'दोनों का लंच ले लेना', 'झगड़ा नजरअंदाज करना'], 1),
  ('teacher', 'Rose of the Day',
   'A child comes clean but troubles the other children all day. Can he be the Rose of the Day?',
   'एक बच्चा साफ-सुथरा आता है लेकिन पूरे दिन दूसरे बच्चों को परेशान करता है। क्या वह “आज का गुलाब” बन सकता है?',
   ARRAY['Yes, because he stays clean', 'Yes, because he comes on time', 'No — good behaviour and discipline have to be considered too', 'Yes, because every child should get a turn'],
   ARRAY['हाँ, क्योंकि वह साफ रहता है', 'हाँ, क्योंकि वह समय पर आता है', 'नहीं, अच्छे व्यवहार और अनुशासन को भी ध्यान में रखना है', 'हाँ, क्योंकि सभी बच्चों को बारी-बारी से देना है'], 2),
  ('teacher', 'Lateness',
   'A child behaves very well but comes late to school again and again. What should the teacher do?',
   'एक बच्चा बहुत अच्छा व्यवहार करता है लेकिन लगातार स्कूल देर से आता है। शिक्षक को क्या करना चाहिए?',
   ARRAY['Give the award and overlook the lateness', 'Explain the importance of coming on time to both the child and the parents', 'Remove him from school', 'Delete his attendance'],
   ARRAY['Award देकर समय की समस्या को नजरअंदाज करना', 'बच्चे और माता-पिता दोनों को समय पर आने के महत्व के बारे में समझाना', 'उसे स्कूल से निकाल देना', 'उसकी अटेंडेंस हटाना'], 1),
  ('teacher', 'Cleanliness',
   'The teacher finds that a child has been coming without clean clothes for several days. What is the most suitable step?',
   'शिक्षक को पता चलता है कि एक बच्चा कई दिनों से बिना साफ कपड़ों के आ रहा है। सबसे उचित कदम क्या है?',
   ARRAY['Shame the child in front of everyone', 'Speak to the parents respectfully and explain why cleanliness matters', 'Separate the child from the others', 'Stop the child from coming to school'],
   ARRAY['बच्चे को सबके सामने शर्मिंदा करना', 'माता-पिता से सम्मानपूर्वक बात करके स्वच्छता का महत्व समझाना', 'बच्चे को दूसरे बच्चों से अलग करना', 'बच्चे को स्कूल आने से रोकना'], 1),
  ('teacher', 'Daily routine',
   'The teacher has several morning duties — prayer, the photograph and attendance. What should she make sure of first?',
   'शिक्षक के पास सुबह कई काम हैं—प्रार्थना, फोटो और अटेंडेंस। उन्हें सबसे पहले क्या सुनिश्चित करना चाहिए?',
   ARRAY['Completing every duty at its set time and in the right order', 'Chatting with the children first', 'Looking at her phone first', 'Putting attendance off until lunch'],
   ARRAY['सभी निर्धारित समय और जिम्मेदारियों को सही क्रम में पूरा करना', 'पहले बच्चों से बातें करना', 'पहले अपना फोन देखना', 'अटेंडेंस को लंच तक टालना'], 0),
  ('teacher', 'Discipline',
   'A teacher sees that the children are following all these rules only out of fear. What should she do?',
   'एक शिक्षक देखती हैं कि बच्चे इन सभी नियमों को केवल डर की वजह से मान रहे हैं। शिक्षक को क्या करना चाहिए?',
   ARRAY['Increase the fear', 'Explain the reason behind the rules and build the habit with affection and encouragement', 'Punish every mistake', 'Do away with the rules'],
   ARRAY['डर और बढ़ाना', 'बच्चों को नियमों का कारण समझाकर प्यार और प्रोत्साहन से आदत विकसित करना', 'हर गलती पर सजा देना', 'नियम हटा देना'], 1)
ON CONFLICT (for_role, question_hi) DO NOTHING;
