-- Sixty situations, and the counselling reason each one points to.
--
-- These are the reasons a teacher ticks when they flag a child, so the test
-- is the flagging itself: read what is in front of you, and name it. The
-- Hindi is the office's wording; the English options are the reasons as the
-- app words them, so what is learned here is what is clicked there.
--
-- The options were shuffled once, with a fixed seed: on the sheet as written
-- the answer was B two times out of three, which teaches the habit rather
-- than the judgement.
INSERT INTO staff_test_questions
  (for_role, topic, question_en, question_hi, options_en, options_hi, correct_index)
VALUES
  ('teacher', 'Spotting a child who needs the mentor',
   'Reena has been taught adding and subtracting for two months and is still stuck counting on her fingers.',
   'रीना को जोड़-घटाव 2 महीने से समझाया जा रहा है पर वो अभी भी उंगलियों पर ही अटकी है।',
   ARRAY['Falling behind in class', 'Withdrawn or very quiet', 'Child is working', 'Frequently absent'],
   ARRAY['कक्षा में पिछड़ रहा है', 'गुमसुम रहता है', 'बच्चा काम कर रहा है', 'अक्सर अनुपस्थित रहता है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'Aman is missing every Monday and Tuesday, with no word from home.',
   'अमन हर हफ्ते सोमवार-मंगलवार गायब रहता है, बिना कोई खबर दिए।',
   ARRAY['Speech or hearing difficulty', 'Health or nutrition concern', 'Risk of dropping out', 'Frequently absent'],
   ARRAY['बोलने में कठिनाई', 'स्वास्थ्य की चिंता', 'स्कूल छोड़ने का खतरा', 'अक्सर अनुपस्थित रहता है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'Sonu, who used to put his hand up most, has sat alone in the corner for a fortnight.',
   'जो सोनू पहले सबसे ज्यादा हाथ उठाता था, अब 15 दिन से कोने में अकेला बैठता है।',
   ARRAY['Falling behind in class', 'Withdrawn or very quiet', 'Disruptive in class', 'Parents not engaging'],
   ARRAY['कक्षा में पिछड़ रहा है', 'गुमसुम या बहुत शांत रहता है', 'शरारत डालता है', 'माता-पिता ध्यान नहीं दे रहे'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The class is going on and Vikas shouts loudly on purpose.',
   'क्लास चल रही है और विकास जानबूझकर तेज-तेज चिल्लाता है।',
   ARRAY['Bullying other children', 'Health or nutrition concern', 'Disruptive in class', 'Signs of neglect at home'],
   ARRAY['दूसरे बच्चों को सता रहा है', 'स्वास्थ्य की चिंता', 'कक्षा में शरारत / बाधा डालता है', 'घर में उपेक्षा'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'Little Pooja comes crying: “the older children take my tiffin every day.”',
   'छोटी पूजा रोते हुए आई “बड़े बच्चे रोज मेरा टिफिन छीन लेते हैं।”',
   ARRAY['Risk of dropping out', 'Bullied by other children', 'Falling behind in class', 'Child is working'],
   ARRAY['स्कूल छोड़ने का खतरा', 'दूसरे बच्चों द्वारा सताया जा रहा है', 'कक्षा में पिछड़ रहा है', 'बच्चा काम कर रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'Sahil pushes the smaller children and breaks their pencils every day.',
   'साहिल रोज़ छोटे बच्चों को धक्का देता है, पेंसिल तोड़ देता है।',
   ARRAY['Withdrawn or very quiet', 'Signs of neglect at home', 'Disruptive in class', 'Bullying other children'],
   ARRAY['गुमसुम रहता है', 'घर में उपेक्षा', 'कक्षा में शरारत डालता है', 'दूसरे बच्चों को सता रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'Aarav comes unwashed in torn clothes every day, with lice in his hair.',
   'आरव रोज़ बिना नहाए, फटे कपड़ों में आता है और बालों में जुएं हैं।',
   ARRAY['Parents not engaging', 'Signs of neglect at home', 'Frequently absent', 'Health or nutrition concern'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'घर में उपेक्षा के लक्षण', 'अक्सर अनुपस्थित', 'स्वास्थ्य की चिंता'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'You have sent word about the PTM three times and his parents never come.',
   'आप 3 बार PTM का संदेश भेजते हैं पर उसके माता-पिता कभी नहीं आते।',
   ARRAY['Child is working', 'Frequently absent', 'Parents not engaging', 'Risk of dropping out'],
   ARRAY['बच्चा काम कर रहा है', 'अक्सर अनुपस्थित रहता है', 'माता-पिता ध्यान नहीं दे रहे हैं', 'स्कूल छोड़ने का खतरा'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'Twelve-year-old Raju washes plates at a hotel in the afternoons, so he sleeps in class.',
   '12 साल का राजू दोपहर में होटल में प्लेट धोने जाता है इसलिए क्लास में सो जाता है।',
   ARRAY['Signs of neglect at home', 'Health or nutrition concern', 'Falling behind in class', 'Child is working'],
   ARRAY['घर में उपेक्षा', 'स्वास्थ्य की चिंता', 'कक्षा में पिछड़ रहा है', 'बच्चा काम कर रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'Seema looks very weak, has stomach aches again and again and faints.',
   'सीमा बहुत कमजोर दिखती है, बार-बार पेट दर्द और चक्कर खाकर गिर जाती है।',
   ARRAY['Signs of neglect at home', 'Withdrawn or very quiet', 'Health or nutrition concern', 'Falling behind in class'],
   ARRAY['घर में उपेक्षा', 'गुमसुम रहता है', 'स्वास्थ्य या पोषण से संबंधित चिंता', 'कक्षा में पिछड़ रहा है'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The teacher calls from behind and Ajay does not hear.',
   'शिक्षक पीछे से आवाज देते हैं पर अजय को सुनाई नहीं देता।',
   ARRAY['Falling behind in class', 'Withdrawn or very quiet', 'Speech or hearing difficulty', 'Bullied by other children'],
   ARRAY['कक्षा में पिछड़ रहा है', 'गुमसुम रहता है', 'बोलने या सुनने में कठिनाई', 'दूसरे द्वारा सताया जा रहा है'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'Fourteen-year-old Anjali says, “my wedding is next month, so I am not to come to school.”',
   '14 साल की अंजलि बोली “अगले महीने मेरी शादी है, अब स्कूल मत जा।”',
   ARRAY['Child is working', 'Health or nutrition concern', 'Risk of dropping out', 'Parents not engaging'],
   ARRAY['बच्चा काम कर रहा है', 'स्वास्थ्य की चिंता', 'स्कूल छोड़ने का खतरा', 'माता-पिता ध्यान नहीं दे रहे'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child knows the answer but writes every letter the wrong way round.',
   'बच्चा सवाल का जवाब जानता है पर लिखते समय सारे अक्षर उल्टे लिख देता है।',
   ARRAY['Disruptive in class', 'Falling behind in class', 'Withdrawn or very quiet', 'Bullying other children'],
   ARRAY['शरारत डालता है', 'कक्षा में पिछड़ रहा है', 'गुमसुम रहता है', 'दूसरों को सता रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'A girl says, “I set out for the centre but had to work at the shop.”',
   'बच्ची कहती है “मैं सेंटर के लिए निकली थी पर दुकान पर काम करना पड़ा।”',
   ARRAY['Health or nutrition concern', 'Child is working', 'Parents not engaging', 'Frequently absent'],
   ARRAY['स्वास्थ्य की चिंता', 'बच्चा काम कर रहा है', 'माता-पिता ध्यान नहीं दे रहे', 'अक्सर अनुपस्थित'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child sits at the very back, will not meet your eye and says not a word.',
   'बच्चा सबसे पीछे बैठता है, आँख नहीं मिलाता, एक शब्द नहीं बोलता।',
   ARRAY['Speech or hearing difficulty', 'Falling behind in class', 'Bullied by other children', 'Withdrawn or very quiet'],
   ARRAY['बोलने में कठिनाई', 'कक्षा में पिछड़ रहा है', 'सताया जा रहा है', 'गुमसुम या बहुत शांत रहता है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “what good is studying — I will go and earn like my brother.”',
   'बच्चा कहता है “पढ़कर क्या होगा, मैं भी भाई की तरह कमाने जाऊंगा।”',
   ARRAY['Parents not engaging', 'Risk of dropping out', 'Child is working', 'Falling behind in class'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'स्कूल छोड़ने का खतरा', 'बच्चा काम कर रहा है', 'कक्षा में पिछड़ रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'Every day the child says “madam, I am hungry”, and his stomach is swollen.',
   'बच्चा रोज कहता है “मैडम भूख लगी है” और पेट फूला हुआ है।',
   ARRAY['Child is working', 'Health or nutrition concern', 'Signs of neglect at home', 'Frequently absent'],
   ARRAY['बच्चा काम कर रहा है', 'स्वास्थ्य या पोषण से संबंधित चिंता', 'घर में उपेक्षा', 'अक्सर अनुपस्थित'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The girl''s mother says, “what is the use of educating her — she is learning the housework.”',
   'बच्ची की माँ कहती है “इसको पढ़ाकर क्या करना, घर का काम सीख रही है।”',
   ARRAY['Parents not engaging', 'Risk of dropping out', 'Signs of neglect at home', 'Child is working'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे हैं', 'स्कूल छोड़ने का खतरा', 'घर में उपेक्षा', 'बच्चा काम कर रहा है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child walks in, tears another child''s notebook and laughs.',
   'बच्चा क्लास में आते ही दूसरे बच्चे की कॉपी फाड़ देता है और हँसता है।',
   ARRAY['Bullying other children', 'Withdrawn or very quiet', 'Disruptive in class', 'Falling behind in class'],
   ARRAY['दूसरे बच्चों को सता रहा है', 'गुमसुम रहता है', 'शरारत डालता है', 'कक्षा में पिछड़ रहा है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child has not come for ten days; it turns out he is going to the brick kiln.',
   'बच्चा 10 दिन से नहीं आ रहा, पता चला ईंट-भट्ठे पर जा रहा है।',
   ARRAY['Health or nutrition concern', 'Risk of dropping out', 'Child is working', 'Frequently absent'],
   ARRAY['स्वास्थ्य की चिंता', 'स्कूल छोड़ने का खतरा', 'बच्चा काम कर रहा है', 'अक्सर अनुपस्थित'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says ''ta'' for ''ka'' and does not follow even when it is repeated twice.',
   'बच्चा ''क'' को ''त'' बोलता है और 2 बार बोलने पर भी नहीं समझ पाता।',
   ARRAY['Falling behind in class', 'Withdrawn or very quiet', 'Health or nutrition concern', 'Speech or hearing difficulty'],
   ARRAY['कक्षा में पिछड़ रहा है', 'गुमसुम रहता है', 'स्वास्थ्य की चिंता', 'बोलने या सुनने में कठिनाई'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “sir, they will not let me play and they tease me.”',
   'बच्चा कहता है “सर, वो सब मुझे खेलने नहीं लेते और चिढ़ाते हैं।”',
   ARRAY['Risk of dropping out', 'Bullied by other children', 'Withdrawn or very quiet', 'Disruptive in class'],
   ARRAY['स्कूल छोड़ने का खतरा', 'दूसरे बच्चों द्वारा सताया जा रहा है', 'गुमसुम रहता है', 'शरारत डालता है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child''s clothes smell, his nails are long and he is always alone.',
   'बच्चे के कपड़े में बदबू, नाखून बड़े हैं और वो हमेशा अकेला रहता है।',
   ARRAY['Parents not engaging', 'Health or nutrition concern', 'Child is working', 'Signs of neglect at home'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'स्वास्थ्य की चिंता', 'बच्चा काम कर रहा है', 'घर में उपेक्षा के लक्षण'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child takes the day off with a stomach ache every time there is a test.',
   'बच्चा हर टेस्ट वाले दिन पेट दर्द का बहाना बनाकर छुट्टी करता है।',
   ARRAY['Withdrawn or very quiet', 'Health or nutrition concern', 'Frequently absent', 'Falling behind in class'],
   ARRAY['गुमसुम रहता है', 'स्वास्थ्य की चिंता', 'अक्सर अनुपस्थित रहता है', 'कक्षा में पिछड़ रहा है'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child stands up on the bench in class and claps.',
   'बच्चा क्लास में बेंच पर खड़ा हो जाता है, ताली बजाता है।',
   ARRAY['Disruptive in class', 'Risk of dropping out', 'Speech or hearing difficulty', 'Bullying other children'],
   ARRAY['कक्षा में शरारत / बाधा डालता है', 'स्कूल छोड़ने का खतरा', 'बोलने में कठिनाई', 'दूसरे बच्चों को सता रहा है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child has been stuck on ABCD for six months while the rest are making sentences.',
   'बच्चा 6 महीने से ABCD पर ही अटका है जबकि बाकी वाक्य बना रहे हैं।',
   ARRAY['Speech or hearing difficulty', 'Withdrawn or very quiet', 'Falling behind in class', 'Parents not engaging'],
   ARRAY['बोलने में कठिनाई', 'गुमसुम रहता है', 'कक्षा में पिछड़ रहा है', 'माता-पिता ध्यान नहीं दे रहे'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'A girl says, “father says girls do not need much schooling.”',
   'बच्ची बोली “पापा कहते हैं लड़कियों को ज्यादा पढ़ने की जरूरत नहीं।”',
   ARRAY['Risk of dropping out', 'Parents not engaging', 'Signs of neglect at home', 'Child is working'],
   ARRAY['स्कूल छोड़ने का खतरा', 'माता-पिता ध्यान नहीं दे रहे', 'घर में उपेक्षा', 'बच्चा काम कर रहा है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child wears a hearing aid and still cannot hear from the front bench.',
   'बच्चा कान में मशीन लगाता है, फिर भी अगली बेंच से सुन नहीं पाता।',
   ARRAY['Speech or hearing difficulty', 'Falling behind in class', 'Withdrawn or very quiet', 'Health or nutrition concern'],
   ARRAY['बोलने या सुनने में कठिनाई', 'कक्षा में पिछड़ रहा है', 'गुमसुम रहता है', 'स्वास्थ्य की चिंता'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “I will not come to school, I do not enjoy it here.”',
   'बच्चा कहता है “मैं स्कूल नहीं आऊंगा, यहाँ मजा नहीं आता।”',
   ARRAY['Child is working', 'Bullied by other children', 'Frequently absent', 'Falling behind in class'],
   ARRAY['बच्चा काम कर रहा है', 'दूसरे बच्चों द्वारा सताया जा रहा है', 'अक्सर अनुपस्थित', 'कक्षा में पिछड़ रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The parents say, “we cannot read — do not show it to us.”',
   'माता-पिता बोले “हमें पढ़ना नहीं आता, हमें मत दिखाओ।”',
   ARRAY['Health or nutrition concern', 'Signs of neglect at home', 'Risk of dropping out', 'Parents not engaging'],
   ARRAY['स्वास्थ्य की चिंता', 'घर में उपेक्षा', 'स्कूल छोड़ने का खतरा', 'माता-पिता ध्यान नहीं दे रहे हैं'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child arrives exhausted and says he worked all night.',
   'बच्चा आते ही थका-हारा रहता है, कहता है रात भर काम किया।',
   ARRAY['Falling behind in class', 'Frequently absent', 'Health or nutrition concern', 'Child is working'],
   ARRAY['कक्षा में पिछड़ रहा है', 'अक्सर अनुपस्थित', 'स्वास्थ्य की चिंता', 'बच्चा काम कर रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child is late every day because he has to look after the younger ones at home.',
   'बच्चा रोज़ लेट आता है क्योंकि घर पर छोटे भाई-बहन को संभालना पड़ता है।',
   ARRAY['Frequently absent', 'Child is working', 'Parents not engaging', 'Signs of neglect at home'],
   ARRAY['अक्सर अनुपस्थित', 'बच्चा काम कर रहा है', 'माता-पिता ध्यान नहीं दे रहे', 'घर में उपेक्षा के लक्षण'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child speaks to nobody in class and eats lunch alone.',
   'बच्चा क्लास में किसी से बात नहीं करता, लंच भी अकेले खाता है।',
   ARRAY['Withdrawn or very quiet', 'Falling behind in class', 'Speech or hearing difficulty', 'Bullied by other children'],
   ARRAY['गुमसुम या बहुत शांत रहता है', 'कक्षा में पिछड़ रहा है', 'बोलने में कठिनाई', 'दूसरे द्वारा सताया जा रहा है'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child pours water into the other children''s bags on purpose.',
   'बच्चा जानबूझकर दूसरे बच्चों के बैग में पानी डाल देता है।',
   ARRAY['Signs of neglect at home', 'Bullying other children', 'Parents not engaging', 'Disruptive in class'],
   ARRAY['घर में उपेक्षा', 'दूसरे बच्चों को सता रहा है', 'माता-पिता ध्यान नहीं दे रहे', 'कक्षा में शरारत डालता है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The girl is very thin, her hair is falling out and she cannot concentrate.',
   'बच्ची बहुत दुबली है, बाल झड़ रहे हैं, ध्यान नहीं दे पाती।',
   ARRAY['Speech or hearing difficulty', 'Health or nutrition concern', 'Signs of neglect at home', 'Falling behind in class'],
   ARRAY['बोलने में कठिनाई', 'स्वास्थ्य या पोषण से संबंधित चिंता', 'घर में उपेक्षा', 'कक्षा में पिछड़ रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “my father has told me to go and earn — no more schooling.”',
   'बच्चा कहता है “मेरे पापा ने कहा अब कमाने चल, पढ़ाई बंद।”',
   ARRAY['Frequently absent', 'Parents not engaging', 'Risk of dropping out', 'Child is working'],
   ARRAY['अक्सर अनुपस्थित', 'माता-पिता ध्यान नहीं दे रहे', 'स्कूल छोड़ने का खतरा', 'बच्चा काम कर रहा है'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child has not come for two weeks; his mother says he is helping in the fields.',
   'बच्चा 2 हफ्ते से नहीं आया, माँ बोली “खेत में हाथ बंटा रहा है।”',
   ARRAY['Signs of neglect at home', 'Risk of dropping out', 'Child is working', 'Frequently absent'],
   ARRAY['घर में उपेक्षा', 'स्कूल छोड़ने का खतरा', 'बच्चा काम कर रहा है', 'अक्सर अनुपस्थित रहता है'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child cannot repeat what the teacher said properly even after two or three goes.',
   'बच्चा टीचर की बात को 2-3 बार में भी ठीक से दोहरा नहीं पाता।',
   ARRAY['Speech or hearing difficulty', 'Withdrawn or very quiet', 'Falling behind in class', 'Health or nutrition concern'],
   ARRAY['बोलने या सुनने में कठिनाई', 'गुमसुम रहता है', 'कक्षा में पिछड़ रहा है', 'स्वास्थ्य की चिंता'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “nobody at home loves me.”',
   'बच्चा बोला “घर पर कोई मुझसे प्यार नहीं करता।”',
   ARRAY['Withdrawn or very quiet', 'Bullied by other children', 'Signs of neglect at home', 'Risk of dropping out'],
   ARRAY['गुमसुम रहता है', 'दूसरे द्वारा सताया जा रहा है', 'घर में उपेक्षा के लक्षण', 'स्कूल छोड़ने का खतरा'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child starts crying as he comes into class: “I am frightened here.”',
   'बच्चा क्लास में आते ही रोने लगता है “यहाँ डर लगता है।”',
   ARRAY['Withdrawn or very quiet', 'Bullied by other children', 'Disruptive in class', 'Risk of dropping out'],
   ARRAY['गुमसुम रहता है', 'दूसरे बच्चों द्वारा सताया जा रहा है', 'शरारत डालता है', 'स्कूल छोड़ने का खतरा'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'Radha brings her homework every day but it is half done and full of mistakes.',
   'राधा होमवर्क तो रोज लाती है पर कॉपी में आधा-अधूरा और बहुत गलत लिखती है।',
   ARRAY['Health or nutrition concern', 'Withdrawn or very quiet', 'Speech or hearing difficulty', 'Falling behind in class'],
   ARRAY['स्वास्थ्य की चिंता', 'गुमसुम रहता है', 'बोलने में कठिनाई', 'कक्षा में पिछड़ रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'Sameer comes for fifteen days a month and stays at home the other fifteen without a word.',
   'समीर महीने में 15 दिन आता है, 15 दिन बिना बताए घर बैठा रहता है।',
   ARRAY['Child is working', 'Parents not engaging', 'Frequently absent', 'Risk of dropping out'],
   ARRAY['बच्चा काम कर रहा है', 'माता-पिता ध्यान नहीं दे रहे', 'अक्सर अनुपस्थित रहता है', 'स्कूल छोड़ने का खतरा'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'All the children are playing but Nikhil sits alone, facing the wall.',
   'सब बच्चे खेल रहे हैं पर निखिल अकेला दीवार की तरफ मुंह करके बैठा है।',
   ARRAY['Bullied by other children', 'Speech or hearing difficulty', 'Falling behind in class', 'Withdrawn or very quiet'],
   ARRAY['दूसरे द्वारा सताया जा रहा है', 'बोलने में कठिनाई', 'कक्षा में पिछड़ रहा है', 'गुमसुम या बहुत शांत रहता है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The teacher is teaching and Karan keeps banging the bench and teasing the others.',
   'टीचर पढ़ा रही हैं और करण बार-बार बेंच बजाता है, दूसरों को चिढ़ाता है।',
   ARRAY['Parents not engaging', 'Disruptive in class', 'Bullying other children', 'Falling behind in class'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'कक्षा में शरारत / बाधा डालता है', 'दूसरे बच्चों को सता रहा है', 'कक्षा में पिछड़ रहा है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'Little Amit says, “didi, they shut me in the bathroom every day.”',
   'छोटा अमित बोला “दीदी, वो रोज मुझे बाथरूम में बंद कर देते हैं।”',
   ARRAY['Disruptive in class', 'Bullied by other children', 'Signs of neglect at home', 'Withdrawn or very quiet'],
   ARRAY['शरारत डालता है', 'दूसरे बच्चों द्वारा सताया जा रहा है', 'घर में उपेक्षा', 'गुमसुम रहता है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'Rani pulls the smaller girls'' hair and makes them cry.',
   'रानी अपने से छोटी बच्चियों के बाल खींचती है और रुलाती है।',
   ARRAY['Parents not engaging', 'Disruptive in class', 'Bullying other children', 'Signs of neglect at home'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'कक्षा में शरारत डालता है', 'दूसरे बच्चों को सता रहा है', 'घर में उपेक्षा'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'There are burn or beating marks on the child''s arms and legs.',
   'बच्चे के हाथ-पैर पर जलने / मारने के निशान हैं।',
   ARRAY['Bullied by other children', 'Disruptive in class', 'Signs of neglect at home', 'Health or nutrition concern'],
   ARRAY['दूसरे द्वारा सताया जा रहा है', 'शरारत डालता है', 'घर में उपेक्षा के लक्षण', 'स्वास्थ्य की चिंता'], 2),
  ('teacher', 'Spotting a child who needs the mentor',
   'The mother says, “you see to it, madam — we have no time.”',
   'माँ कहती है “आप ही देख लो मैडम, हमारे पास टाइम नहीं है।”',
   ARRAY['Child is working', 'Frequently absent', 'Risk of dropping out', 'Parents not engaging'],
   ARRAY['बच्चा काम कर रहा है', 'अक्सर अनुपस्थित', 'स्कूल छोड़ने का खतरा', 'माता-पिता ध्यान नहीं दे रहे हैं'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child picks rags in the morning and comes to the centre in the afternoon.',
   'बच्चा सुबह कचरा बीनता है, दोपहर सेंटर आता है।',
   ARRAY['Signs of neglect at home', 'Frequently absent', 'Health or nutrition concern', 'Child is working'],
   ARRAY['घर में उपेक्षा', 'अक्सर अनुपस्थित', 'स्वास्थ्य की चिंता', 'बच्चा काम कर रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child''s eyes are yellow, his stomach is swollen and he weighs very little.',
   'बच्चे की आँखें पीली हैं, पेट फूला है और वजन बहुत कम है।',
   ARRAY['Health or nutrition concern', 'Falling behind in class', 'Child is working', 'Signs of neglect at home'],
   ARRAY['स्वास्थ्य या पोषण से संबंधित चिंता', 'कक्षा में पिछड़ रहा है', 'बच्चा काम कर रहा है', 'घर में उपेक्षा'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'A girl says ''la'' for ''ra'', the children laugh, and she stops speaking.',
   'बच्ची ''र'' को ''ल'' बोलती है इसलिए बच्चे हँसते हैं तो वो बोलना बंद कर देती है।',
   ARRAY['Falling behind in class', 'Speech or hearing difficulty', 'Bullied by other children', 'Withdrawn or very quiet'],
   ARRAY['कक्षा में पिछड़ रहा है', 'बोलने या सुनने में कठिनाई', 'दूसरे द्वारा सताया जा रहा है', 'गुमसुम रहता है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'A thirteen-year-old says, “father says stop studying and go to Delhi to work.”',
   '13 साल का लड़का बोला “पापा कह रहे हैं अब पढ़ाई बंद, दिल्ली जाकर काम कर।”',
   ARRAY['Child is working', 'Risk of dropping out', 'Parents not engaging', 'Frequently absent'],
   ARRAY['बच्चा काम कर रहा है', 'स्कूल छोड़ने का खतरा', 'माता-पिता ध्यान नहीं दे रहे', 'अक्सर अनुपस्थित'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child forgets even counting to ten while the rest count to a hundred.',
   'बच्चा 10 तक गिनती भी भूल जाता है, जबकि बाकी 100 तक गिन लेते हैं।',
   ARRAY['Falling behind in class', 'Speech or hearing difficulty', 'Withdrawn or very quiet', 'Health or nutrition concern'],
   ARRAY['कक्षा में पिछड़ रहा है', 'बोलने में कठिनाई', 'गुमसुम रहता है', 'स्वास्थ्य की चिंता'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'A girl takes three or four days off every month with a stomach ache as the excuse.',
   'बच्ची हर महीने 3-4 दिन पेट दर्द का बहाना करके छुट्टी करती है।',
   ARRAY['Parents not engaging', 'Signs of neglect at home', 'Health or nutrition concern', 'Frequently absent'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'घर में उपेक्षा', 'स्वास्थ्य की चिंता', 'अक्सर अनुपस्थित रहता है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The teacher called his name and the child started — he heard only at the third call.',
   'टीचर ने नाम पुकारा तो बच्चा चौंक गया, 3 बार बुलाने पर ही सुनाई दिया।',
   ARRAY['Falling behind in class', 'Speech or hearing difficulty', 'Disruptive in class', 'Withdrawn or very quiet'],
   ARRAY['कक्षा में पिछड़ रहा है', 'बोलने या सुनने में कठिनाई', 'शरारत डालता है', 'गुमसुम रहता है'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “mother and father fight every day, I do not like it at home.”',
   'बच्चा कहता है “मम्मी-पापा रोज लड़ते हैं, मुझे घर पर अच्छा नहीं लगता।”',
   ARRAY['Health or nutrition concern', 'Bullied by other children', 'Withdrawn or very quiet', 'Signs of neglect at home'],
   ARRAY['स्वास्थ्य की चिंता', 'दूसरे द्वारा सताया जा रहा है', 'गुमसुम रहता है', 'घर में उपेक्षा के लक्षण'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “I have no friends, everyone teases me, so I will not come.”',
   'बच्चा कहता है “मेरा कोई दोस्त नहीं है, सब चिढ़ाते हैं इसलिए मैं नहीं आऊंगा।”',
   ARRAY['Bullied by other children', 'Withdrawn or very quiet', 'Risk of dropping out', 'Frequently absent'],
   ARRAY['दूसरे बच्चों द्वारा सताया जा रहा है', 'गुमसुम रहता है', 'स्कूल छोड़ने का खतरा', 'अक्सर अनुपस्थित'], 0),
  ('teacher', 'Spotting a child who needs the mentor',
   'A girl says, “I will not come tomorrow, I have to look after my little brother at home.”',
   'बच्ची बोली “मैं कल नहीं आऊंगी, मुझे घर पर छोटे भाई को संभालना पड़ता है।”',
   ARRAY['Parents not engaging', 'Signs of neglect at home', 'Frequently absent', 'Child is working'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे', 'घर में उपेक्षा', 'अक्सर अनुपस्थित', 'बच्चा काम कर रहा है'], 3),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child suddenly loses his temper in class, bangs the bench and tears his notebook.',
   'बच्चा क्लास में अचानक गुस्सा, बेंच पटकता है, कॉपी फाड़ देता है।',
   ARRAY['Bullying other children', 'Disruptive in class', 'Signs of neglect at home', 'Risk of dropping out'],
   ARRAY['दूसरे बच्चों को सता रहा है', 'कक्षा में शरारत / बाधा डालता है', 'घर में उपेक्षा', 'स्कूल छोड़ने का खतरा'], 1),
  ('teacher', 'Spotting a child who needs the mentor',
   'The child says, “madam, I will not study after class 8 — the family says no.”',
   'बच्चा बोला “मैडम, अब मैं 8वीं के बाद नहीं पढूंगा, घरवाले मना कर रहे हैं।”',
   ARRAY['Parents not engaging', 'Falling behind in class', 'Child is working', 'Risk of dropping out'],
   ARRAY['माता-पिता ध्यान नहीं दे रहे हैं', 'कक्षा में पिछड़ रहा है', 'बच्चा काम कर रहा है', 'स्कूल छोड़ने का खतरा'], 3)
ON CONFLICT (for_role, question_hi) DO NOTHING;
